##############################################################################
# Dockstore Configuration for AltAnalyze2 SNAF Workflows
##############################################################################
# This file configures automatic workflow registration with Dockstore
# For more info: https://docs.dockstore.org/en/stable/getting-started/dockstore-yml.html
##############################################################################

version: 1.2

workflows:
  - name: splicing_analysis
    subclass: WDL
    primaryDescriptorPath: /workflows/splicing_analysis/splicing_analysis.wdl
    testParameterFiles:
      - /workflows/splicing_analysis/inputs/test.json
    authors:
      - name: "Valerii Pavlov"
        email: "valerii.pavlov@fccc.com"
        orcid: "0000-0002-8139-9978"
    
    # Documentation links
    readMePath: /README.md
    
    # Container information
    publish: true
    
    # Version filters (optional - matches semantic versioning tags)
    filters:
      branches:
        - main
      tags:
        - /^v\d+\.\d+\.\d+$/

  - name: star_2pass_alignment
    subclass: WDL
    primaryDescriptorPath: /star_2.4_alignment/star_alignment.wdl
    testParameterFiles:
      - /star_2.4_alignment/star_alignment_test.json
    authors:
      - name: "Valerii Pavlov"
        email: "valerii.pavlov@fccc.com"
        orcid: "0000-0002-8139-9978"
    
    # Documentation links
    readMePath: /star_2.4_alignment/README.md
    
    # Container information
    publish: true
    
    # Version filters (optional - matches semantic versioning tags)
    filters:
      branches:
        - main
      tags:
        - /^v\d+\.\d+\.\d+$/

##############################################################################
# Workflow Features:
# - Multi-platform Docker support (AMD64/ARM64)
# - Containerized execution with reproducible environments
# - Automatic resource scaling based on input data size
# - Compatible with Terra, Cromwell, and other WDL engines
# - Comprehensive splicing and alignment analysis pipelines
##############################################################################