##############################################################################
# Dockstore Configuration for AltAnalyze2 SNAF Workflows
##############################################################################
# This file configures automatic workflow registration with Dockstore
# For more info: https://docs.dockstore.org/en/stable/getting-started/dockstore-yml.html
##############################################################################

version: 1.2

workflows:
  - name: splicing_analysis
    subclass: WDL
    primaryDescriptorPath: /splicing_analysis.wdl
    testParameterFiles:
      - /splicing_analysis_test.json
    authors:
      - name: "Valerii Pavlov"
        email: "valerii.pavlov@fccc.com"
        orcid: "https://orcid.org/0000-0002-8139-9978"
    description: >
      AltAnalyze splicing analysis workflow for RNA-seq BAM files.
      Performs comprehensive alternative splicing analysis including
      exon inclusion, intron retention, and splice site identification.
      Supports single-sample and comparative analysis modes.
    
    # Workflow metadata
    topics:
      - "RNA-seq"
      - "splicing"
      - "alternative-splicing"
      - "exon-inclusion"
      - "bioinformatics"
      - "genomics"
    
    # Documentation links
    readMePath: /README.md
    
    # Container information
    publish: true
    
    # Version filters (optional - matches semantic versioning tags)
    filters:
      branches:
        - main
      tags:
        - /^v\d+\.\d+\.\d+$/

  - name: star_2pass_alignment
    subclass: WDL
    primaryDescriptorPath: /star_2.4_alignment/star_alignment.wdl
    testParameterFiles:
      - /star_2.4_alignment/star_alignment_test.json
    authors:
      - name: "Valerii Pavlov"
        email: "valerii.pavlov@fccc.com"
        orcid: "https://orcid.org/0000-0002-8139-9978"
    description: >
      STAR 2-pass RNA-seq alignment workflow for paired-end sequencing data.
      This workflow performs a two-pass alignment strategy where the first pass
      detects novel splice junctions and the second pass uses this information
      for improved alignment accuracy. Ideal for discovering novel isoforms
      and splice variants in RNA-seq datasets.
    
    # Workflow metadata
    topics:
      - "RNA-seq"
      - "STAR"
      - "alignment"
      - "splice-junction"
      - "bioinformatics"
      - "genomics"
    
    # Documentation links
    readMePath: /star_2.4_alignment/README.md
    
    # Container information
    publish: true
    
    # Version filters (optional - matches semantic versioning tags)
    filters:
      branches:
        - main
      tags:
        - /^v\d+\.\d+\.\d+$/

##############################################################################
# Workflow Features:
# - Multi-platform Docker support (AMD64/ARM64)
# - Containerized execution with reproducible environments
# - Automatic resource scaling based on input data size
# - Compatible with Terra, Cromwell, and other WDL engines
# - Comprehensive splicing and alignment analysis pipelines
##############################################################################