#!/bin/bash

cd /mnt/disks/cromwell_root
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /mnt/disks/cromwell_root
ln -s /mnt/disks/cromwell_root /cromwell_root
)


outc7fb51df="${tmpDir}/out.$$" errc7fb51df="${tmpDir}/err.$$"
mkfifo "$outc7fb51df" "$errc7fb51df"
trap 'rm "$outc7fb51df" "$errc7fb51df"' EXIT
touch '/mnt/disks/cromwell_root/stdout' '/mnt/disks/cromwell_root/stderr'
tee '/mnt/disks/cromwell_root/stdout' < "$outc7fb51df" &
tee '/mnt/disks/cromwell_root/stderr' < "$errc7fb51df" >&2 &
(
cd /mnt/disks/cromwell_root


set -euo pipefail
mkdir -p /mnt/bam
cp "/mnt/disks/cromwell_root/fc-secure-e0503432-75b9-4674-8e6d-2597dc529c4c/GTEx_Analysis_2022-06-06_v10_RNAseq_BAM_files/GTEX-11DXZ-1926-SM-5GZZL.Aligned.sortedByCoord.out.patched.md.bam" /mnt/bam/
cp "/mnt/disks/cromwell_root/fc-secure-e0503432-75b9-4674-8e6d-2597dc529c4c/GTEx_Analysis_2022-06-06_v10_RNAseq_BAM_files/GTEX-11DXZ-1926-SM-5GZZL.Aligned.sortedByCoord.out.patched.md.bam.bai" /mnt/bam/

bn=$(basename "/mnt/disks/cromwell_root/fc-secure-e0503432-75b9-4674-8e6d-2597dc529c4c/GTEx_Analysis_2022-06-06_v10_RNAseq_BAM_files/GTEX-11DXZ-1926-SM-5GZZL.Aligned.sortedByCoord.out.patched.md.bam")
/usr/src/app/AltAnalyze.sh bam_to_bed "bam/${bn}"

# Move outputs to task dir
shopt -s nullglob
for f in /mnt/bam/*.bed; do
    cp "$f" ./
done
)  > "$outc7fb51df" 2> "$errc7fb51df"
echo $? > /mnt/disks/cromwell_root/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /mnt/disks/cromwell_root
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /mnt/disks/cromwell_root
sync
# make the directory which will keep the matching files
mkdir /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /mnt/disks/cromwell_root/*.bed /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5 2> /dev/null ) || ( ln /mnt/disks/cromwell_root/*.bed /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5 | grep -v cromwell_glob_control_file > /mnt/disks/cromwell_root/glob-2d1abde47b9c06d87a549d7187f55ad5.list


)
mv /mnt/disks/cromwell_root/rc.tmp /mnt/disks/cromwell_root/rc

