name: ShellCheck

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck (non-blocking)
        run: |
          set -euo pipefail
          # Find and lint shell scripts (excluding generated/downloaded artifacts)
          shopt -s globstar nullglob
          all=( **/*.sh )
          files=()
          for f in "${all[@]}"; do
            [[ "$f" == gcs_downloads/* ]] && continue
            files+=( "$f" )
          done
          if [ ${#files[@]} -gt 0 ]; then
            # Do not fail the workflow on findings; surface them only
            shellcheck --severity=style --format=gcc "${files[@]}" || true
          else
            echo "No shell scripts found; skipping ShellCheck."
          fi
