name: WDL Validation

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install miniwdl
        run: |
          pip install --upgrade pip
          pip install miniwdl

      - name: Download womtool
        run: |
          WOMTOOL_VERSION=86
          curl -L -o womtool.jar https://github.com/broadinstitute/cromwell/releases/download/${WOMTOOL_VERSION}/womtool-${WOMTOOL_VERSION}.jar

      - name: Validate WDLs under workflows/ with womtool
        run: |
          set -euo pipefail
          mapfile -t WDL_FILES < <(git ls-files 'workflows/**/*.wdl')
          echo "Validating ${#WDL_FILES[@]} WDL files: ${WDL_FILES[*]}"
          for f in "${WDL_FILES[@]}"; do
            echo "--- womtool validate: $f"
            java -jar womtool.jar validate "$f"
          done

      - name: Lint WDLs under workflows/ with miniwdl
        run: |
          set -euo pipefail
          mapfile -t WDL_FILES < <(git ls-files 'workflows/**/*.wdl')
          for f in "${WDL_FILES[@]}"; do
            echo "--- miniwdl check: $f"
            miniwdl check "$f"
          done
